### ISSUE TITLE
老哥搞的不错啊，已经star，如果response的JSON能高亮一下就更好了

### ISSUE THREAD

**Issue by fantasyado** [zy445566/before-server#3]
就是key和value不一样颜色就行，这样看着清楚点

**Comment by zy445566** [comment]
嗯，可以的，这几天改一下。

还是第一次有人说这个不错的，感觉之前点赞的都是没使用过的，因为感觉这个东西理解起来有点复杂，嗯但是作为开发环境的抓包工具确实效果不错。

**Comment by zy445566** [comment]
高亮JSON完成 @fantasyado 
npm install -g before-server@1.0.51

那issue关闭了
