### ISSUE TITLE
怎么重写目标路径？

### ISSUE THREAD

**Issue by UILKUNP** [zy445566/before-server#5]
类似于devServer的pathRewrite，
例如，我把web界面(默认端口8555) 转发到 /log 
当我访问 localhost:httpPort(80)/log/时，我想得到的是  localhost:8555/
而不是  localhost:8555/log

```js
 "/log": {
      target: "http://127.0.0.1:8555", //你的测试域名,当访问代理的api1开头的url要代理的开发服务
      cors: true, // 如果要配置cors跨域可以在这里设置
      changeOrigin: true, // 如果后端对域名有识别，可以配置这个
      tag: "监控室", // 配置标签
      pathRewrite: {
        "^/log": "",
      },
    },
``

**Comment by zy445566** [comment]
我觉得你理解错了。api访问的只是8000或8443端口，他和UI界面的8555端口是没有任何关系的，等等下午我给你发个示例。我现在在团建

**Comment by UILKUNP** [comment]
感谢，可能我表述的有些问题，api使用了httpPort和httpsPort这两个端口，在这两个端口下做的路径转发，我把httpPort设为80，配置一条规则：
`"/proxyServer": {
      target: "https://api.github.com",
      cors: true, 
      changeOrigin: true, // 如果后端对域名有识别，可以配置这个
      tag: "代理GIThubApi" // 配置标签
    },`
此时我访问 localhost/proxyServer 相当于访问了 https://api.github.com/proxyServer，但是 https://api.github.com后面是不需要 /proxyServer 这个路径的，devServe中有一个路径重写，可以把 target的路径修改
`pathRewrite: {
        "^/proxyServer": "",
  }
`

**Comment by zy445566** [comment]
嗯，我仔细看了下这个选项是http-proxy-middleware而不是http-proxy的选项。没想过webpack-dev-server基于http-proxy加了功能。你的配置貌似是没问题的。是我的失误，今天下午我就把pathRewrite移植一下，抱歉

**Comment by zy445566** [comment]
搞定了,试试
```sh
 npm install -g before-server@1.0.55
```
记得重启服务才能生效哦

**Comment by zy445566** [comment]
你这边可以了吗？

**Comment by fantasyado** [comment]
path rewrite 之后监控页面出问题了，只能监控全部

**Comment by UILKUNP** [comment]
抱歉 才看到,path rewrite已经可以了 ，强强强👍👍👍

**Comment by zy445566** [comment]
> path rewrite 之后监控页面出问题了，只能监控全部
这个在1.0.58版本中修复了
```sh
 npm install -g before-server@1.0.58
```

**Comment by fantasyado** [comment]
> > path rewrite 之后监控页面出问题了，只能监控全部
> 
> 这个在1.0.58版本中修复了
> 
> ```shell
>  npm install -g before-server@1.0.58
> ```
> 
> @fantasyado 如果好了，能在这个issue跟我说下么，我好关闭issue了。感谢🙏

嗯嗯，这个可以了， 不过我测试的时候代理到百度发现response乱码，不知道是不是中文的原因呢

![image](https://user-images.githubusercontent.com/10321851/102679261-61dd2380-41e9-11eb-8963-6b4e5126a1ed.png)

**Comment by zy445566** [comment]
> 嗯嗯，这个可以了， 不过我测试的时候代理到百度发现response乱码，不知道是不是中文的原因呢

这个不是中文原因导致的，是因为https的不对称加密导致，但是只是抓取有问题实际访问其实是可以的。
我的配置
```js
proxyTable:{
        '/test': {
            target: 'https://www.baidu.com', //重写服务地址示例
            tag:'重写百度服务', // 配置标签
            changeOrigin: true, // 注意百度对域名有识别，否则无法打开
            pathRewrite: {
                "^/test": "", 
            },
        },
    },
```
我打开的地址是：https://127.0.0.1:8443/test 
目前是正常的，针对乱码问题，我新开了个issue，打算周一再解决了
