### ISSUE TITLE
有一些请求的cookie没有带上，导致请求失败

### ISSUE THREAD

**Issue by fantasyado** [zy445566/before-server#6]
我们的服务部署在AWS上，比如cookie里面有 AWSALB=YXLGC+t+mH7i02Yab9/0rb3ZdhAjqOnmRW7aEJItfC9/eC6cPs/ZFMfRC5StA/45FGwh1W7OYjvmhCfYXAqUapqS9x7gMqPlaa/y/BgH5gwOg6jWwpDw7UvhP7BI 之类的东西用来确定之前处理请求的服务器，不带上的话session就会丢失，老哥看看有办法修吗

**Comment by zy445566** [comment]
可以修，我先研究下

**Comment by fantasyado** [comment]
嗯， 我把代码下下来了，就是在proxy.js里面把，我也试试

**Comment by fantasyado** [comment]
> 可以修，我先研究下

我发现有的请求query会加一个时间戳，&_=1608184441720 这个是在哪里处理的

**Comment by fantasyado** [comment]
> 可以修，我先研究下

改了下可以了，在proxy.on('proxyRes'） 把set-cookie header存起来，然后请求的时候塞进去就好了，没搞清楚为啥每次response的set-cookie会变，所以只取第一次的了
![image](https://user-images.githubusercontent.com/10321851/102450929-777c0d00-4072-11eb-8a5d-a73fa69131d0.png)
![image](https://user-images.githubusercontent.com/10321851/102450957-882c8300-4072-11eb-9e56-6117737a6b6a.png)

**Comment by zy445566** [comment]
很奇怪，我这里测试的是没问题的，我测试的服务代码是这样的
```js
const http = require('http')
const proxy = http.createServer((req, res) => {
    res.setHeader('set-cookie',`session_key=${Math.random()}; expires=Thu, 31 Dec 2020 08:29:18 GMT; httponly; Path=/`)
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end(req.url);
  }).listen(7957)
```
我的代理配置是这样的
```js
proxyTable:{
        '/': {
            target: 'http://127.0.0.1:7957',
            // cookieDomainRewrite:"",
            tag:"根目录"
        },
    },
```
我怀疑你的服务是不是带域了，你可以试一下使用cookieDomainRewrite清除域，和尝试使用cookiePathRewrite重写域

**Comment by zy445566** [comment]
你这边可以了吗？

**Comment by fantasyado** [comment]
> 你这边可以了吗？

昨天下午出了个线上问题 还没来得及试，不过你说的服务带域我因为做App的还不太懂需要研究下

**Comment by zy445566** [comment]
> 昨天下午出了个线上问题 还没来得及试，不过你说的服务带域我因为做App的还不太懂需要研究下

就是cookie有域名限制，只有在指定域名才生效

**Comment by fantasyado** [comment]
> > 昨天下午出了个线上问题 还没来得及试，不过你说的服务带域我因为做App的还不太懂需要研究下
> 
> 就是cookie有域名限制，只有在指定域名才生效。如果是这样，你可以直接加cookieDomainRewrite配置来实现清除域名限制，从而实现在客户端生效，修改配置后要记得重启服务。
> 
> 如果不是这个原因，最好你把一个完整的set-cookie头给我，因为在测试的时候发现set-cookie头，before-server是会带set-cookie过去的

这个是我登录之后的set-cookie：

`set-cookie : AWSALB=YwdnAvmzqklioD2fnLoaQosk93hu4vVsO+i1JuXONuEXXhKsQqjFfL17vWoO4KYBjFLa3q34b7ZmfN37WdnGGFZZhmern3bwexjpMg05Kh+3dhIIybKrttpS2+Ct; Expires=Fri, 25 Dec 2020 05:50:28 GMT; Path=/,AWSALBCORS=YwdnAvmzqklioD2fnLoaQosk93hu4vVsO+i1JuXONuEXXhKsQqjFfL17vWoO4KYBjFLa3q34b7ZmfN37WdnGGFZZhmern3bwexjpMg05Kh+3dhIIybKrttpS2+Ct; Expires=Fri, 25 Dec 2020 05:50:28 GMT; Path=/; SameSite=None; Secure,JSESSIONID=EB9F54624CC390FC21C99CC7F926ADC5.ue1-qa1-aspiraone-web-01; Path=/; Secure; HttpOnly`

**Comment by zy445566** [comment]
。。。兄弟跟我这个before-server没关系，你的cookie设置了Secure，必须要在https的环境下才能够使用，我建议你使用8443端口，最好配置好证书。
你可以直接调用8443端口，看看是不是好了

**Comment by fantasyado** [comment]
> 。。。兄弟跟我这个before-server没关系，你的cookie设置了Secure，必须要在https的环境下才能够使用，否则不会设置cookie的。我建议你使用before-server的https端口，默认是8443端口，最好配置好证书。如果使用8443端口取代8000端口，api请求地址的http别忘记修改为https。
> 你可以直接调用before-server的https端口，看看是不是好了

我换成 https的话直接请求失败，监控列表里也看不到请求过来

**Comment by zy445566** [comment]
> 我换成 https的话直接请求失败，监控列表里也看不到请求过来 . 算了就用 http方式的workaround吧，刚搜了下根据StackOverFlow [link](https://stackoverflow.com/questions/21162097/node-js-string-replace-doesnt-work) 把cookie里的secure过滤掉也可以

请求失败是因为客户端api协议要改成https的同时还需要使用8443端口，其次还有一种可能就是你证书严格校验了，你可以把某个接口请求放到浏览器中看一下就知道了

**Comment by fantasyado** [comment]
> > 我换成 https的话直接请求失败，监控列表里也看不到请求过来 . 算了就用 http方式的workaround吧，刚搜了下根据StackOverFlow [link](https://stackoverflow.com/questions/21162097/node-js-string-replace-doesnt-work) 把cookie里的secure过滤掉也可以
> 
> 请求失败是因为客户端api协议要改成https的同时还需要使用8443端口，其次还有一种可能就是你证书严格校验了，你可以把某个接口请求放到浏览器中看一下就知道了。
> 我不建议你使用replace的方式，建议你还是使用https保持一致最好

端口我肯定改了的，浏览器里返回未登录像这样，能看出什么吗
![image](https://user-images.githubusercontent.com/10321851/102595816-360f5e80-4153-11eb-9ac0-1ed43881daf9.png)

**Comment by zy445566** [comment]
> 端口我肯定改了的，浏览器里返回未登录像这样，能看出什么吗

协议你修改了吗？端口要和api请求地址的协议一模一样的

**Comment by fantasyado** [comment]
> > 端口我肯定改了的，浏览器里返回未登录像这样，能看出什么吗
> 
> 协议你修改了吗？端口要和api请求地址的协议一模一样的。就是你APP的请求接口地址的协议。如果不是这个原因，那只能看看什么时候约一个远程桌面了。
> 
> 。。。话说这个图我也看不出什么，你是给before-server服务套了个域名么？

我理解错了，你是要看从浏览器访问代理地址是把。。我试了下都是乱码

![image](https://user-images.githubusercontent.com/10321851/102678861-1ecd8100-41e6-11eb-84e7-fec0ed1e25c0.png)
这是我的配置：

![image](https://user-images.githubusercontent.com/10321851/102678869-30af2400-41e6-11eb-8772-cca801c81a69.png)

**Comment by zy445566** [comment]
> 我理解错了，你是要看从浏览器访问代理地址是把。。我试了下都是乱码

那你暂时使用8000端口吧，还有你这个问题可以添加secure: false关闭依赖，乱码问题，我开了个新issue来解决，你下次配置发文字吧，我这边截图不同的电脑可能不带翻墙，看不太到。

**Comment by zy445566** [comment]
乱码问题已经解决了，是由于网站开启了gzip功能导致，现在1.0.60版本已支持gzip读取

**Comment by fantasyado** [comment]
> > 我理解错了，你是要看从浏览器访问代理地址是把。。我试了下都是乱码
> 
> 那你暂时使用8000端口吧，还有你这个问题可以添加配置secure: false关闭cookie的https依赖，乱码问题，我开了个新issue来解决，你下次配置发文字吧，我这边截图不同的电脑可能不带翻墙，看不太到。
> 
> 另外我觉得你这个报500是不是因为你这个页面本身是不需要重写的，页面的url输入错误了？那个乱码貌似是befoer-server报的错，我已经修改了，当然主因是没有匹配到URL（ [eb39e00](https://github.com/zy445566/before-server/commit/eb39e00d3e8117286e91e8c379c229983925ed54) ）。

嗯试了下，用http协议配置secure:false 确实可以，https应该证书相关的问题，我在postman里访问里一下报：Could not get response SSL Error: Self signed certificate，然后他有一个设置 Enable SSL certificate verification， 关掉就可以。

**Comment by zy445566** [comment]
OK,那没问题，这个issue我就关了
