### ISSUE TITLE
feature:增加修复https端口(默认8443端口)抓包显示乱码问题

### ISSUE THREAD

**Issue by zy445566** [zy445566/before-server#7]
这是由于https的RSA加密未解析所导致的抓包乱码问题，目前建议暂时使用http端口(默认8000端口)来读取抓包，如果存在secure建议增加配置secure:false

**Comment by zy445566** [comment]
@fantasyado 
经排查发现和https无关，是由于开启了gzip，显示的是压缩后的数据
此问题在1.0.60版本修复
安装方式：
```sh
npm install before-server@1.0.60
```

**Comment by fantasyado** [comment]
response还是会乱码，不知道啥原因，用的最新1.0.7版本
![image](https://user-images.githubusercontent.com/10321851/114355947-a0d12380-9ba2-11eb-8271-c27e2449120e.png)

**Comment by zy445566** [comment]
> response还是会乱码，不知道啥原因，用的最新1.0.7版本
> ![image](https://user-images.githubusercontent.com/10321851/114355947-a0d12380-9ba2-11eb-8271-c27e2449120e.png)

最新版本是1.0.70啊

**Comment by zy445566** [comment]
> > response还是会乱码，不知道啥原因，用的最新1.0.7版本
> > ![image](https://user-images.githubusercontent.com/10321851/114355947-a0d12380-9ba2-11eb-8271-c27e2449120e.png)
> 
> 最新版本是1.0.70啊，还有就是是全部乱码，还是部分页面乱码？
